# Permalinks
permalink:           :title

# Setup
title:               mikelothar.com
tagline:
url:                 http://mikelothar.com
paginate:            1000
baseurl:             ""
analytics_id:        UA-77750213-1

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mike Lothar
  url:
  email:

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/mikelothar/mikelothar

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

markdown: kramdown

excerpt_separator: "\n\n"

exclude:
  - CNAME
  - LICENSE.md
